# Generated by Django 5.1.3 on 2024-11-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passenger_trip_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferryboat',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
