# Generated by Django 5.1.3 on 2024-11-26 11:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ferryboat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferryboat',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
