# Generated by Django 5.1.3 on 2024-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='boarding_status',
            field=models.CharField(choices=[('NOT_CHECKED_IN', 'Not Checked-in'), ('CHECKED_IN', 'Checked-in'), ('BOARDED', 'Boarded'), ('MISSED', 'Missed'), ('OFFBOARDED', 'Offboarded')], default='NOT_CHECKED_IN', max_length=15),
        ),
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
