# Generated by Django 5.1.3 on 2025-04-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_passenger_boarding_status_passenger_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='contact',
        ),
    ]
