# Generated by Django 5.1.3 on 2025-05-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ticket_qr_code_ticket_cash_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='boarding_status',
            field=models.CharField(choices=[('NOT_BOARDED', 'Not Boarded'), ('BOARDED', 'Boarded'), ('CANCELLED', 'Cancelled')], default='NOT_BOARDED', max_length=15),
        ),
    ]
