# Generated by Django 5.1.3 on 2025-05-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_passenger_boarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
