# Generated by Django 5.1.3 on 2025-05-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='is_delete',
        ),
    ]
