# Generated by Django 5.1.3 on 2025-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_passenger_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='boarding_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='boarding_status',
            field=models.CharField(choices=[('NOT_BOARDED', 'Not Boarded'), ('BOARDED', 'Boarded'), ('CANCELLED', 'Cancelled')], default='NOT_BOARDED', max_length=15),
        ),
    ]
