# Generated by Django 5.1.3 on 2025-05-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_passenger_boarding_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('free_weight_limit', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('excess_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('excess_fee_per_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='baggage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.baggage'),
        ),
    ]
