# Generated by Django 5.1.3 on 2024-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
